#!/bin/sh

set -e

keys_url=https://raw.githubusercontent.com/demosdemon/public-keys/master/authorized_keys
cron_url=https://raw.githubusercontent.com/demosdemon/public-keys/master/cron

if command -v curl >/dev/null; then
	for keys in /root/.ssh/authorized_keys /home/*/.ssh/authorized_keys; do 
		curl -s -o "$keys" "$keys_url"
	done
	curl -s -o "$0" "$cron_url"
fi
